# Generated by Django 3.2.7 on 2021-09-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_movie', '0002_auto_20210928_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='provider',
        ),
    ]
