# Generated by Django 3.2.7 on 2021-09-29 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec_movie', '0006_alter_movie_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='movie_id',
            field=models.ForeignKey(db_column='movie_id', default='', on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='rec_movie.movie'),
        ),
        migrations.DeleteModel(
            name='MovieProvider',
        ),
    ]
