# Generated by Django 3.2.7 on 2021-09-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_movie', '0010_moviegenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
