# Generated by Django 3.2.7 on 2021-09-29 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec_movie', '0011_delete_moviegenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_movie.genre')),
                ('movie_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_movie.movie')),
            ],
        ),
    ]
