# Generated by Django 3.2.7 on 2021-10-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price_per_day', models.PositiveIntegerField()),
                ('logo_url', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartyJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('user', models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('member_limit', models.IntegerField()),
                ('service_id', models.EmailField(max_length=254)),
                ('service_password', models.CharField(max_length=100)),
                ('end_date', models.DateTimeField()),
                ('price_per_day', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('payments', models.ManyToManyField(related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
