# Generated by Django 3.2.7 on 2021-09-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('personnel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('party_start_date', models.DateTimeField()),
                ('party_end_date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('rule_age', models.BooleanField(default=False)),
                ('rule_assign', models.BooleanField(default=False)),
                ('rule_share', models.BooleanField(default=False)),
                ('rull_refund', models.BooleanField(default=False)),
                ('detail_content', models.TextField()),
            ],
        ),
    ]
