# Generated by Django 3.2.7 on 2021-10-01 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('member_limit', models.IntegerField()),
                ('service_id', models.EmailField(max_length=254)),
                ('service_password', models.CharField(max_length=100)),
                ('end_date', models.DateTimeField()),
                ('price_per_day', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('host', models.ManyToManyField(related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
